spring:
  application:
    test: false
    url: http://localhost:8080/api/v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/anyservice_db?currentSchema=anyservice
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: anyservicePoolName
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  zone:
    offset:
      hours: 1
  user:
    verification:
      seconds: 259200 # 3 days
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  mail:
    host: smtp.yandex.ru
    port: 587
    username: byaxe@ya.ru
    password:
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000

user:
  validation:
    email:
      allow:
        local: true # allow local email addresses - "true" for development purposes
    password:
      rounds: 12
      length:
        min: 8
        max: 50

security:
  inner:
    header: x-y-z-token
    key: 68fbea20-b11a-4326-987d-7ff3cfeab81b
  ttl:
    period: 7200000
  jwt:
    uuid:
      live:
        seconds: 120
    param:
      token:
        name: token
    never: 1691300640540
    key: LKJIDJFV1aswZ
    header: JX-TOKEN

#s3:
#  enable: true
#  type: amazon
#  defaultStorage: http://192.168.192.12:9000
#  storages:
#    "[http://192.168.192.12:9000]":
#      endpoint: http://192.168.192.12:9000
#      access_key: KMG3ZZUZ57R2U85VTUJF
#      secret_key: C3V6aGA1bOJEUbIRhnwwQisKlj1TTSUrhazou0Hq
#      bucket: anyservice
#      region: us-east-1
#      maxUploadSize: 2147483647
